# Generated by Django 2.1.1 on 2018-10-13 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0002_collage_registered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('contact', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('pic', models.FileField(upload_to='images/%Y/%m/%d')),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='cbvapp.Collage')),
            ],
        ),
    ]
